"""
Proposals Router - Export and format proposal content
"""
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from datetime import datetime

from database import get_db, Analysis, Document

router = APIRouter()


@router.get("/{analysis_id}/export/markdown", response_class=PlainTextResponse)
async def export_proposal_markdown(analysis_id: int, db: AsyncSession = Depends(get_db)):
    """Export proposal as Markdown"""
    result = await db.execute(select(Analysis).where(Analysis.id == analysis_id))
    analysis = result.scalar_one_or_none()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    
    # Get document info
    doc_result = await db.execute(select(Document).where(Document.id == analysis.document_id))
    document = doc_result.scalar_one_or_none()
    
    doc_name = document.original_filename if document else "RFP Document"
    
    markdown = f"""# Proposal for {doc_name}

**Generated by ProposalPilot AI**  
**Date:** {datetime.now().strftime("%B %d, %Y")}  
**AI Model:** {analysis.model_used or "Qwen 2.5 7B"}

---

## Executive Summary

{analysis.executive_summary or "Not generated yet."}

---

## Requirements Analysis

{analysis.requirements or "Not generated yet."}

---

## Clarification Questions

{analysis.clarification_questions or "Not generated yet."}

---

## Risk Assessment

{analysis.risks or "Not generated yet."}

---

## Key Assumptions

{analysis.assumptions or "Not generated yet."}

---

## Proposal Outline

{analysis.proposal_outline or "Not generated yet."}

---

*Generated by ProposalPilot AI - Powered by Ollama (local AI)*
"""
    return markdown


@router.get("/{analysis_id}/summary")
async def get_proposal_summary(analysis_id: int, db: AsyncSession = Depends(get_db)):
    """Get proposal summary stats"""
    result = await db.execute(select(Analysis).where(Analysis.id == analysis_id))
    analysis = result.scalar_one_or_none()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    
    def count_items(text):
        if not text:
            return 0
        return len([l for l in text.split("\n") if l.strip() and (l.strip().startswith("-") or l.strip()[0].isdigit())])
    
    return {
        "analysis_id": analysis_id,
        "status": analysis.status,
        "requirements_count": count_items(analysis.requirements),
        "questions_count": count_items(analysis.clarification_questions),
        "risks_count": count_items(analysis.risks),
        "assumptions_count": count_items(analysis.assumptions),
        "has_executive_summary": bool(analysis.executive_summary),
        "has_proposal_outline": bool(analysis.proposal_outline),
        "model_used": analysis.model_used,
        "created_at": analysis.created_at
    }
